add support spi nor flash

diff --git a/tools/testing/selftests/ftrace/ftracetest b/tools/testing/selftests/ftrace/ftracetest
--- a/tools/testing/selftests/ftrace/ftracetest
+++ b/tools/testing/selftests/ftrace/ftracetest
@@ -8,18 +8,15 @@
 # Released under the terms of the GPL v2.
 
 usage() { # errno [message]
-[ ! -z "$2" ] && echo $2
+[ "$2" ] && echo $2
 echo "Usage: ftracetest [options] [testcase(s)] [testcase-directory(s)]"
 echo " Options:"
 echo "		-h|--help  Show help message"
 echo "		-k|--keep  Keep passed test logs"
 echo "		-v|--verbose Increase verbosity of test messages"
 echo "		-vv        Alias of -v -v (Show all results in stdout)"
-echo "		-vvv       Alias of -v -v -v (Show all commands immediately)"
-echo "		--fail-unsupported Treat UNSUPPORTED as a failure"
 echo "		-d|--debug Debug mode (trace all shell commands)"
 echo "		-l|--logdir <dir> Save logs on the <dir>"
-echo "		            If <dir> is -, all logs output in console only"
 exit $1
 }
 
@@ -50,7 +47,7 @@ parse_opts() { # opts
   local OPT_TEST_CASES=
   local OPT_TEST_DIR=
 
-  while [ ! -z "$1" ]; do
+  while [ "$1" ]; do
     case "$1" in
     --help|-h)
       usage 0
@@ -59,18 +56,13 @@ parse_opts() { # opts
       KEEP_LOG=1
       shift 1
     ;;
-    --verbose|-v|-vv|-vvv)
+    --verbose|-v|-vv)
       VERBOSE=$((VERBOSE + 1))
       [ $1 = '-vv' ] && VERBOSE=$((VERBOSE + 1))
-      [ $1 = '-vvv' ] && VERBOSE=$((VERBOSE + 2))
       shift 1
     ;;
     --debug|-d)
       DEBUG=1
-      shift 1
-    ;;
-    --fail-unsupported)
-      UNSUPPORTED_RESULT=1
       shift 1
     ;;
     --logdir|-l)
@@ -96,7 +88,7 @@ parse_opts() { # opts
     ;;
     esac
   done
-  if [ ! -z "$OPT_TEST_CASES" ]; then
+  if [ "$OPT_TEST_CASES" ]; then
     TEST_CASES=$OPT_TEST_CASES
   fi
 }
@@ -116,7 +108,6 @@ LOG_DIR=$TOP_DIR/logs/`date +%Y%m%d-%H%M%S`/
 KEEP_LOG=0
 DEBUG=0
 VERBOSE=0
-UNSUPPORTED_RESULT=0
 # Parse command-line options
 parse_opts $*
 
@@ -128,20 +119,14 @@ if [ -z "$TRACING_DIR" -o ! -d "$TRACING_DIR" ]; then
 fi
 
 # Preparing logs
-if [ "x$LOG_DIR" = "x-" ]; then
-  LOG_FILE=
-  date
-else
-  LOG_FILE=$LOG_DIR/ftracetest.log
-  mkdir -p $LOG_DIR || errexit "Failed to make a log directory: $LOG_DIR"
-  date > $LOG_FILE
-fi
-
+LOG_FILE=$LOG_DIR/ftracetest.log
+mkdir -p $LOG_DIR || errexit "Failed to make a log directory: $LOG_DIR"
+date > $LOG_FILE
 prlog() { # messages
-  [ -z "$LOG_FILE" ] && echo "$@" || echo "$@" | tee -a $LOG_FILE
+  echo "$@" | tee -a $LOG_FILE
 }
 catlog() { #file
-  [ -z "$LOG_FILE" ] && cat $1 || cat $1 | tee -a $LOG_FILE
+  cat $1 | tee -a $LOG_FILE
 }
 prlog "=== Ftrace unit tests ==="
 
@@ -202,7 +187,7 @@ eval_result() { # sigval
     $UNSUPPORTED)
       prlog "	[UNSUPPORTED]"
       UNSUPPORTED_CASES="$UNSUPPORTED_CASES $CASENO"
-      return $UNSUPPORTED_RESULT # depends on use case
+      return 1 # this is not a bug, but the result should be reported.
     ;;
     $XFAIL)
       prlog "	[XFAIL]"
@@ -262,20 +247,12 @@ __run_test() { # testfile
 # Run one test case
 run_test() { # testfile
   local testname=`basename $1`
-  if [ ! -z "$LOG_FILE" ] ; then
-    local testlog=`mktemp $LOG_DIR/${testname}-log.XXXXXX`
-  else
-    local testlog=/proc/self/fd/1
-  fi
+  local testlog=`mktemp $LOG_DIR/${testname}-log.XXXXXX`
   export TMPDIR=`mktemp -d /tmp/ftracetest-dir.XXXXXX`
   testcase $1
   echo "execute$INSTANCE: "$1 > $testlog
   SIG_RESULT=0
-  if [ -z "$LOG_FILE" ]; then
-    __run_test $1 2>&1
-  elif [ $VERBOSE -ge 3 ]; then
-    __run_test $1 | tee -a $testlog 2>&1
-  elif [ $VERBOSE -eq 2 ]; then
+  if [ $VERBOSE -ge 2 ]; then
     __run_test $1 2>> $testlog | tee -a $testlog
   else
     __run_test $1 >> $testlog 2>&1
@@ -283,9 +260,9 @@ run_test() { # testfile
   eval_result $SIG_RESULT
   if [ $? -eq 0 ]; then
     # Remove test log if the test was done as it was expected.
-    [ $KEEP_LOG -eq 0 -a ! -z "$LOG_FILE" ] && rm $testlog
+    [ $KEEP_LOG -eq 0 ] && rm $testlog
   else
-    [ $VERBOSE -eq 1 -o $VERBOSE -eq 2 ] && catlog $testlog
+    [ $VERBOSE -ge 1 ] && catlog $testlog
     TOTAL_RESULT=1
   fi
   rm -rf $TMPDIR
